### PR TITLE
Support including specific domains and entities

### LINKED ISSUE #49: Add include_domains and include_entities
**Is your feature request related to a problem? Please describe.**
Currently, the configuration file allows for excluding domains and entities. If one needs to send only few data to ES, then she/he needs to add all other domains to the `exclude_domains` array.

**Describe the solution you'd like**
Add `include_domains` and `include_entities` with a precedence that included entities override excluded domains (and that excluded entities override include domains?).

### PR DESCRIPTION
**Pull request by legrego**
Adds support for including specific domains and entities. This is effectively the opposite of the `exclude_domains` and `exclude_entities` settings that exist today.

Resolves #49

### CODE REVIEW

**Comment by chrgro** [comment]
Any chance this could be merged? It's precisely what I am in need of :)

**Comment by legrego** [comment]
@chrgro sorry for the delayed response. I need to make sure this still works, as this is quite out of date. Would you be able & willing to test this if I were to publish a beta release in the near future with these changes?

**Comment by chrgro** [comment]
Yes, I am more than happy to test a build for you :)

**Comment by legrego** [comment]
@chrgro beta release available here: https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v0.5.0-beta-1

Disclaimer: I haven't tested this myself yet, so I'm sorry in advance if this fails spectacularly.

**Comment by legrego** [comment]
@chrgro I've done some light testing locally, and this seems to be working for me. I've love your iput too though, before I publish a non-beta release.

**Comment by chrgro** [comment]
Thanks, and apologies for the delay. I've done some testing now, and it doesn't entirely seem to work right for me. For testing purposes I'm just setting it up like this:

image


Yet I keep getting uploads for basically all entities:

image

My hope was that it would only upload selected ones, without having to exclude all?

**Comment by chrgro** [comment]
Thanks, and apologies for the delay. I am testing it now. (Ignore my deleted message if you got that in your email).

It does seem to work correctly. My only nitpick is perhaps that it should be better described what happens when you explicitly specify domains to publish. At that point the default for "exclude" is overridden. This is the natural behavior though, it just could've been clearer.

**Comment by chrgro** [comment]
Hmm, I do seem to have stumbled upon some sort of bug. I have this setup:

image

But I still occasionally get all of the entities published:
image

I can't quite determine exactly what the issue is, but it perhaps feels like it publishes all entities without filtering directly after updating the homeassistant-elasticsearch configuration in the UI?

**Comment by legrego** [comment]
@chrgro Thanks so much for taking the time to test and provide feedback, I really appreciate it. I'll see what I can do to make the UX a bit clearer, and try to track down this intermittent publishing bug

**Pull request merged**
