### PR TITLE
Use lru cache for datastream and attribute normalization

### PR DESCRIPTION
**Pull request by strawgate**
Part of https://github.com/legrego/homeassistant-elasticsearch/issues/278

### CODE REVIEW

**Comment by strawgate** [comment]
Should be good to go

**Comment by strawgate** [comment]
Fixes: #293

**Comment by strawgate** [comment]
My environment has 110 devices and ~600 entities. My unique attribute count is 250 which is well below the 1024 threshold. The 1024 is how many attributes can be in a single batch, not total attributes historically.

I may take some time to test how much worse performance gets if the cache starts thrashing as well as how much memory is consumed by the LRU with my current ~250 attributes.

My immediate guess is that the hashing function probably uses sha1 which outputs a constant 20 bytes, and the value is the sanitized name which probably averages at most 10 bytes for 30 bytes per entry * 1024 entries * 30% overhead or about 39kb. I imagine we probably could bump this to be quite large like 8192 or higher and only consume a noticeable amount of memory in particularly large environments in which case the serialization for bulk probably consumes significantly more memory than the memoization.

**Review by legrego — APPROVED** [review]
LGTM, thanks! I think your cache sizes seem quite reasonable for a first release. This is easy enough for us to adjust if we notice performance issues in the wild.

**Pull request merged**
