### PR TITLE
Improve workflow (again)

### PR DESCRIPTION
**Pull request by KTibow**
I made ha-blueprint recently. This merges your existing workflow with the one I made.

### CODE REVIEW

**Review by legrego — COMMENTED** [review]
@KTibow I appreciate you taking the time to put this together!

Regarding `ha-blueprint`, I have a couple of comments:

1) I'm not keen on having the action auto-format code. I might be old school, but I would prefer to handle that within my dev environment prior to committing or pushing changes. I see you expose a configuration option to disable this piece, so if we move forward with this PR, I'd like to see that disabled.
2) It appears like `ha-blueprint` defines its own set of `flake8` rules. I would prefer to maintain the rules within this project's [`.flake8` file](https://github.com/legrego/homeassistant-elasticsearch/blob/master/.flake8). I'm not opposed to altering the current rule set, but I don't want to necessarily tie this project's rules to an external action.
3) I wasn't aware of the `hassfest` action, so I'm glad you've introduced me to that! I'm curious: the [official docs](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) give instructions for integrating `hassfest` into repositories, but it looks like `ha-blueprint` is doing something different than what the [official docs](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) recommend. Can you explain what the differences are, and why you chose your current approach?

**Comment by KTibow** [comment]
1. Sure! I'll go ahead and remove that.
2. I'll add using a predefined flake8 rule list to ha-blueprint when I have time, putting this in my saved notifications. Right now it checks for syntax errors, then installs wemake-python-styleguide (**very strict linting**) and gives you feedback so you can nitpick your code when you have time.
3. No difference, basically the normal way is GitHub Actions builds the docker container and runs it, I'm just reverse-engineering how they did that and doing that if Python files are detected.

**Comment by legrego** [comment]
> 1. Sure! I'll go ahead and remove that.

Thanks!

> 2. I'll add using a predefined flake8 rule list to ha-blueprint when I have time, putting this in my saved notifications. Right now it checks for syntax errors, then installs wemake-python-styleguide (**very strict linting**) and gives you feedback so you can nitpick your code when you have time.

I see. The previous action would actually stop the build if we had violations, and I don't want to lose that. It seems silly to run flake8 twice, but maybe we can add the original check back into this project's workflow?

> 3. No difference, basically the normal way is GitHub Actions builds the docker container and runs it, I'm just reverse-engineering how they did that and doing that if Python files are detected.

Thanks for explaining. Just as an FYI, I'm seeing a warning in the action output when installing `isort` -- not sure if you've seen this or not, but we may require updates soon:
https://github.com/legrego/homeassistant-elasticsearch/runs/1268926009#step:8:875

> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
  Successfully installed isort-5.6.4

> We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

**Comment by KTibow** [comment]
2. What kind of violations? Right now it'll fail on `E9,F63,F7,F82`
3. Don't worry about it, everyone gets it if they update pip.

**Comment by legrego** [comment]
> What kind of violations? Right now it'll fail on E9,F63,F7,F82. 

Ah, I missed this part when reading the action code the first time around.

> What do you mean, the original check? Plain flake8 with no modifications?

Almost without modifications (so far). We're overriding the `max-line-length` right now:

https://github.com/legrego/homeassistant-elasticsearch/blob/ad56b5dc9828de7c413ccd93da966e5e51570121/.flake8#L1-L2

My preference is to have GitHub Actions use the same rules that my IDE uses, so that I can get proper feedback before pushing my changes. Having different rules between the repo's config (`.flake8`) and the GH Actions's config means that I can't rely on my IDE to show me all of the errors that could go wrong. 

Perhaps `ha-blueprint` can ship with `E9,F63,F7,F82` as the default set of rules to fail on, but use the settings configured in the repo if they're provided? That would give other custom components the benefit of your "preferred" rules, while still letting stubborn people like me define their own rule set. What do you think?

**Comment by KTibow** [comment]
Looks good to you now?

**Review by legrego — APPROVED** [review]
Looks great, thanks again @KTibow!

**Comment by KTibow** [comment]
BTW consider opting this repo in to hacktoberfest (just add the topic).

**Pull request merged**
