### PR TITLE
GH actions + format

### PR DESCRIPTION
**Pull request by KTibow**
This adds GitHub Actions, and formats with black and isort.

### CODE REVIEW

**Comment by legrego** [comment]
Hi @KTibow, thanks for taking the time to raise this PR. I'm sorry for not getting to this sooner - I haven't had a chance to review yet, but I haven't forgotten about this!

**Comment by KTibow** [comment]
Actually don't merge, I'm working on a better version of this.

**Comment by KTibow** [comment]
https://github.com/KTibow/ha-blueprint/projects/1

**Comment by legrego** [comment]
> Actually don't merge, I'm working on a better version of this.

Thanks for the heads-up. I'll close this for now then

**Pull request closed without merging**
