### PR TITLE
Enable interactive debugging

### PR DESCRIPTION
**Pull request by strawgate**
Builds on https://github.com/legrego/homeassistant-elasticsearch/pull/231

See this commit for the change that enables interactive debugging:

https://github.com/legrego/homeassistant-elasticsearch/commit/d095038c95462f9be8822a1d0024a2b2db048424

### CODE REVIEW

**Comment by strawgate** [comment]
ready to go once https://github.com/legrego/homeassistant-elasticsearch/pull/231 is merged

**Comment by strawgate** [comment]
Fixes: https://github.com/legrego/homeassistant-elasticsearch/issues/248

**Comment by strawgate** [comment]
I think I need to get the GitHub workflow to correctly run the coverage tests so this may require a couple more iterations

**Comment by strawgate** [comment]
Also launch.json is missing... will fix in it a bit...

**Comment by strawgate** [comment]
yipee, I believe this is ready to merge

**Review by legrego — APPROVED** [review]
LGTM once nit is addressed

**Pull request merged**
